/*
 * This file is generated by jOOQ.
 */
package dev.theagencyhq.agency.db.jooq.tables.records;


import dev.theagencyhq.agency.db.jooq.tables.BriefSources;
import dev.theagencyhq.agency.model.SourceStatus;

import java.time.Instant;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BriefSourcesRecord extends UpdatableRecordImpl<BriefSourcesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.brief_sources.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.brief_sources.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.brief_sources.organization_id</code>.
     */
    public void setOrganizationId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.brief_sources.organization_id</code>.
     */
    public UUID getOrganizationId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.brief_sources.path</code>.
     */
    public void setPath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.brief_sources.path</code>.
     */
    public String getPath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.brief_sources.last_built_commit</code>.
     */
    public void setLastBuiltCommit(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.brief_sources.last_built_commit</code>.
     */
    public String getLastBuiltCommit() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.brief_sources.last_polled_instant</code>.
     */
    public void setLastPolledInstant(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.brief_sources.last_polled_instant</code>.
     */
    public Instant getLastPolledInstant() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>public.brief_sources.last_status</code>.
     */
    public void setLastStatus(SourceStatus value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.brief_sources.last_status</code>.
     */
    public SourceStatus getLastStatus() {
        return (SourceStatus) get(5);
    }

    /**
     * Setter for <code>public.brief_sources.last_error</code>.
     */
    public void setLastError(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.brief_sources.last_error</code>.
     */
    public String getLastError() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.brief_sources.last_pull_error</code>.
     */
    public void setLastPullError(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.brief_sources.last_pull_error</code>.
     */
    public String getLastPullError() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.brief_sources.insert_instant</code>.
     */
    public void setInsertInstant(Instant value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.brief_sources.insert_instant</code>.
     */
    public Instant getInsertInstant() {
        return (Instant) get(8);
    }

    /**
     * Setter for <code>public.brief_sources.update_instant</code>.
     */
    public void setUpdateInstant(Instant value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.brief_sources.update_instant</code>.
     */
    public Instant getUpdateInstant() {
        return (Instant) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BriefSourcesRecord
     */
    public BriefSourcesRecord() {
        super(BriefSources.BRIEF_SOURCES);
    }

    /**
     * Create a detached, initialised BriefSourcesRecord
     */
    public BriefSourcesRecord(UUID id, UUID organizationId, String path, String lastBuiltCommit, Instant lastPolledInstant, SourceStatus lastStatus, String lastError, String lastPullError, Instant insertInstant, Instant updateInstant) {
        super(BriefSources.BRIEF_SOURCES);

        setId(id);
        setOrganizationId(organizationId);
        setPath(path);
        setLastBuiltCommit(lastBuiltCommit);
        setLastPolledInstant(lastPolledInstant);
        setLastStatus(lastStatus);
        setLastError(lastError);
        setLastPullError(lastPullError);
        setInsertInstant(insertInstant);
        setUpdateInstant(updateInstant);
        resetTouchedOnNotNull();
    }
}
