/*
 * This file is generated by jOOQ.
 */
package dev.theagencyhq.agency.db.jooq.tables.records;


import dev.theagencyhq.agency.db.jooq.tables.Briefs;

import java.time.Instant;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BriefsRecord extends UpdatableRecordImpl<BriefsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.briefs.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.briefs.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.briefs.organization_id</code>.
     */
    public void setOrganizationId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.briefs.organization_id</code>.
     */
    public UUID getOrganizationId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.briefs.version</code>.
     */
    public void setVersion(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.briefs.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.briefs.checksum</code>.
     */
    public void setChecksum(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.briefs.checksum</code>.
     */
    public String getChecksum() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.briefs.document</code>.
     */
    public void setDocument(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.briefs.document</code>.
     */
    public String getDocument() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.briefs.source_commit</code>.
     */
    public void setSourceCommit(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.briefs.source_commit</code>.
     */
    public String getSourceCommit() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.briefs.insert_instant</code>.
     */
    public void setInsertInstant(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.briefs.insert_instant</code>.
     */
    public Instant getInsertInstant() {
        return (Instant) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BriefsRecord
     */
    public BriefsRecord() {
        super(Briefs.BRIEFS);
    }

    /**
     * Create a detached, initialised BriefsRecord
     */
    public BriefsRecord(UUID id, UUID organizationId, Integer version, String checksum, String document, String sourceCommit, Instant insertInstant) {
        super(Briefs.BRIEFS);

        setId(id);
        setOrganizationId(organizationId);
        setVersion(version);
        setChecksum(checksum);
        setDocument(document);
        setSourceCommit(sourceCommit);
        setInsertInstant(insertInstant);
        resetTouchedOnNotNull();
    }
}
