/*
 * This file is generated by jOOQ.
 */
package dev.theagencyhq.agency.db.jooq.tables.records;


import dev.theagencyhq.agency.db.jooq.tables.Organizations;

import java.time.Instant;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrganizationsRecord extends UpdatableRecordImpl<OrganizationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.organizations.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.organizations.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.organizations.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.organizations.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.organizations.github_login</code>.
     */
    public void setGithubLogin(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.organizations.github_login</code>.
     */
    public String getGithubLogin() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.organizations.github_access_token</code>.
     */
    public void setGithubAccessToken(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.organizations.github_access_token</code>.
     */
    public String getGithubAccessToken() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.organizations.github_access_expiration</code>.
     */
    public void setGithubAccessExpiration(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.organizations.github_access_expiration</code>.
     */
    public Instant getGithubAccessExpiration() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>public.organizations.github_refresh_token</code>.
     */
    public void setGithubRefreshToken(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.organizations.github_refresh_token</code>.
     */
    public String getGithubRefreshToken() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.organizations.github_refresh_expiration</code>.
     */
    public void setGithubRefreshExpiration(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.organizations.github_refresh_expiration</code>.
     */
    public Instant getGithubRefreshExpiration() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>public.organizations.insert_instant</code>.
     */
    public void setInsertInstant(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.organizations.insert_instant</code>.
     */
    public Instant getInsertInstant() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>public.organizations.update_instant</code>.
     */
    public void setUpdateInstant(Instant value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.organizations.update_instant</code>.
     */
    public Instant getUpdateInstant() {
        return (Instant) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationsRecord
     */
    public OrganizationsRecord() {
        super(Organizations.ORGANIZATIONS);
    }

    /**
     * Create a detached, initialised OrganizationsRecord
     */
    public OrganizationsRecord(UUID id, String name, String githubLogin, String githubAccessToken, Instant githubAccessExpiration, String githubRefreshToken, Instant githubRefreshExpiration, Instant insertInstant, Instant updateInstant) {
        super(Organizations.ORGANIZATIONS);

        setId(id);
        setName(name);
        setGithubLogin(githubLogin);
        setGithubAccessToken(githubAccessToken);
        setGithubAccessExpiration(githubAccessExpiration);
        setGithubRefreshToken(githubRefreshToken);
        setGithubRefreshExpiration(githubRefreshExpiration);
        setInsertInstant(insertInstant);
        setUpdateInstant(updateInstant);
        resetTouchedOnNotNull();
    }
}
