db.password=dev
db.url=jdbc:postgresql://127.0.0.1:5432/the_agency
db.username=dev
fusionauth.apiKey=33052c8a-c283-4e96-9d2a-eb1215c69f8f-not-for-prod
fusionauth.baseURL=http://localhost:9016
fusionauth.clientId=7e1c9a54-0f8b-4a2e-9c6d-3b5f81d0a742
fusionauth.clientSecret=super-secret-secret-that-should-be-regenerated-for-production
fusionauth.handlerClientId=fa83bc7c-f1c5-48af-8ecb-6c09cf766d73
fusionauth.handlerClientSecret=super-secret-secret-that-should-be-regenerated-for-production
fusionauth.issuer=http://localhost:9016
github.appName=the-agency-hq
github.clientId=replace-me
github.clientSecret=replace-me
poller.enabled=true
poller.intervalSeconds=60
runtime.mode=development
web.cookieEncryptionKey=zJ1sQ8ZKk3vYy0Xh2NrTfBpL6cWmA4dEuO9iRgS7VqU=
