/*
 * Copyright (c) 2026 The Agency HQ
 * SPDX-License-Identifier: MIT
 */
package dev.theagencyhq.agency.service.translation;

import module java.base;

/**
 * One source rule — a {@code rules/**.md} file — as {@link SourceTree#rules()} reads it, once, for every Translator
 * that rewrites it.
 *
 * <p>A rule has two scopes. Its {@code paths:} globs are Claude Code's, and every Agent whose rules format has a
 * glob field gets them translated; the others get {@link #bodyWithPathsNote()}, a prose line ahead of the body. Its
 * Mission Types ride on the Brief file, and the Handler filters whole files by them, so a Translator that writes one
 * file per rule never needs to mention them — only a Translator that folds every rule into one document does, via
 * {@link #bodyWithAllNotes()}.
 *
 * @param path         The source path.
 * @param name         The rule's output name: the path beneath {@code rules/} without its extension, with every
 *                     {@code /} replaced by {@code -}. Flat, because several Agents read only the top level of their
 *                     rules directory, and a flat file is read by the recursive ones too.
 * @param paths        The globs from a {@code paths:} frontmatter list, or empty when the rule applies everywhere.
 * @param missionTypes The Mission Types, canonical form.
 * @param body         The Markdown after the frontmatter, stripped.
 */
public record Rule(String path, String name, List<String> paths, List<String> missionTypes, String body) {
  public static final String DIRECTORY = "rules";
  public static final String DOCUMENT_HEADER = "<!-- Generated by The Agency from the rules directory of the Brief "
                                               + "source. Do not edit: the next Brief overwrites this file. -->";
  public static final String DOCUMENT_SEPARATOR = "\n\n---\n\n";
  public static final String PATHS_KEY = "paths";
  private static final String DOCUMENT = """
      %s

      %s
      """;

  /**
   * Folds every rule into one Markdown document, for the Agents whose only always-on instruction channel is a
   * single file or a single configuration value. One document cannot carry a scope per section, so each rule's
   * scope notes go ahead of its section instead, and the document as a whole applies to every Mission Type: the
   * Handler can only filter whole files, so a rule scoped to one Mission Type still travels to every Location and
   * relies on the Agent to honor the note.
   *
   * @param rules  The rules, in path order.
   * @param header Whether to open with {@link #DOCUMENT_HEADER} and end with a newline, as a file should. A value
   *               embedded in a configuration file wants neither.
   * @return The document.
   */
  public static String toRulesDocument(List<Rule> rules, boolean header) {
    var sections = rules.stream().map(Rule::bodyWithAllNotes).collect(Collectors.joining(DOCUMENT_SEPARATOR));
    return header ? DOCUMENT.formatted(DOCUMENT_HEADER, sections) : sections;
  }

  /**
   * @return The body with every scope note ahead of it, for a document that folds many rules into one file.
   */
  public String bodyWithAllNotes() {
    var notes = new ArrayList<String>();
    if (scoped()) {
      notes.add(pathsNote());
    }

    if (!missionTypes.isEmpty()) {
      notes.add("_The following applies only to projects of type " + String.join(", ", missionTypes) + "._");
    }

    return notes.isEmpty() ? body : String.join("\n", notes) + "\n\n" + body;
  }

  /**
   * @return The body with the paths note ahead of it when the rule is scoped, for a per-rule file in a format
   *     without a glob field.
   */
  public String bodyWithPathsNote() {
    return scoped() ? pathsNote() + "\n\n" + body : body;
  }

  /**
   * @return True if the rule declares {@code paths:} globs.
   */
  public boolean scoped() {
    return !paths.isEmpty();
  }

  private String pathsNote() {
    return "_The following applies only to files matching "
           + paths.stream().map(p -> "`" + p + "`").collect(Collectors.joining(", ")) + "._";
  }
}
