/*
 * This file is generated by jOOQ.
 */
package dev.theagencyhq.agency.db.jooq;


import dev.theagencyhq.agency.db.jooq.tables.BriefSources;
import dev.theagencyhq.agency.db.jooq.tables.Briefs;
import dev.theagencyhq.agency.db.jooq.tables.Members;
import dev.theagencyhq.agency.db.jooq.tables.Organizations;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.brief_sources</code>.
     */
    public final BriefSources BRIEF_SOURCES = BriefSources.BRIEF_SOURCES;

    /**
     * The table <code>public.briefs</code>.
     */
    public final Briefs BRIEFS = Briefs.BRIEFS;

    /**
     * The table <code>public.members</code>.
     */
    public final Members MEMBERS = Members.MEMBERS;

    /**
     * The table <code>public.organizations</code>.
     */
    public final Organizations ORGANIZATIONS = Organizations.ORGANIZATIONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            BriefSources.BRIEF_SOURCES,
            Briefs.BRIEFS,
            Members.MEMBERS,
            Organizations.ORGANIZATIONS
        );
    }
}
