/*
 * This file is generated by jOOQ.
 */
package dev.theagencyhq.agency.db.jooq;


import dev.theagencyhq.agency.db.jooq.tables.BriefSources;
import dev.theagencyhq.agency.db.jooq.tables.Briefs;
import dev.theagencyhq.agency.db.jooq.tables.Members;
import dev.theagencyhq.agency.db.jooq.tables.Organizations;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.brief_sources</code>.
     */
    public static final BriefSources BRIEF_SOURCES = BriefSources.BRIEF_SOURCES;

    /**
     * The table <code>public.briefs</code>.
     */
    public static final Briefs BRIEFS = Briefs.BRIEFS;

    /**
     * The table <code>public.members</code>.
     */
    public static final Members MEMBERS = Members.MEMBERS;

    /**
     * The table <code>public.organizations</code>.
     */
    public static final Organizations ORGANIZATIONS = Organizations.ORGANIZATIONS;
}
