/*
 * This file is generated by jOOQ.
 */
package dev.theagencyhq.agency.db.jooq.tables;


import dev.theagencyhq.agency.db.jooq.Indexes;
import dev.theagencyhq.agency.db.jooq.Keys;
import dev.theagencyhq.agency.db.jooq.Public;
import dev.theagencyhq.agency.db.jooq.tables.Organizations.OrganizationsPath;
import dev.theagencyhq.agency.db.jooq.tables.records.BriefsRecord;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Converter;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Briefs extends TableImpl<BriefsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.briefs</code>
     */
    public static final Briefs BRIEFS = new Briefs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BriefsRecord> getRecordType() {
        return BriefsRecord.class;
    }

    /**
     * The column <code>public.briefs.id</code>.
     */
    public final TableField<BriefsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.briefs.organization_id</code>.
     */
    public final TableField<BriefsRecord, UUID> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.briefs.version</code>.
     */
    public final TableField<BriefsRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.briefs.checksum</code>.
     */
    public final TableField<BriefsRecord, String> CHECKSUM = createField(DSL.name("checksum"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.briefs.document</code>.
     */
    public final TableField<BriefsRecord, String> DOCUMENT = createField(DSL.name("document"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.briefs.source_commit</code>.
     */
    public final TableField<BriefsRecord, String> SOURCE_COMMIT = createField(DSL.name("source_commit"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.briefs.insert_instant</code>.
     */
    public final TableField<BriefsRecord, Instant> INSERT_INSTANT = createField(DSL.name("insert_instant"), SQLDataType.BIGINT.nullable(false), this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    private Briefs(Name alias, Table<BriefsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Briefs(Name alias, Table<BriefsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.briefs</code> table reference
     */
    public Briefs(String alias) {
        this(DSL.name(alias), BRIEFS);
    }

    /**
     * Create an aliased <code>public.briefs</code> table reference
     */
    public Briefs(Name alias) {
        this(alias, BRIEFS);
    }

    /**
     * Create a <code>public.briefs</code> table reference
     */
    public Briefs() {
        this(DSL.name("briefs"), null);
    }

    public <O extends Record> Briefs(Table<O> path, ForeignKey<O, BriefsRecord> childPath, InverseForeignKey<O, BriefsRecord> parentPath) {
        super(path, childPath, parentPath, BRIEFS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BriefsPath extends Briefs implements Path<BriefsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BriefsPath(Table<O> path, ForeignKey<O, BriefsRecord> childPath, InverseForeignKey<O, BriefsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BriefsPath(Name alias, Table<BriefsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BriefsPath as(String alias) {
            return new BriefsPath(DSL.name(alias), this);
        }

        @Override
        public BriefsPath as(Name alias) {
            return new BriefsPath(alias, this);
        }

        @Override
        public BriefsPath as(Table<?> alias) {
            return new BriefsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BRIEFS_IDX_ORGANIZATION_VERSION);
    }

    @Override
    public UniqueKey<BriefsRecord> getPrimaryKey() {
        return Keys.BRIEFS_PKEY;
    }

    @Override
    public List<UniqueKey<BriefsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.BRIEFS_ORGANIZATION_ID_VERSION_KEY);
    }

    @Override
    public List<ForeignKey<BriefsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BRIEFS__BRIEFS_ORGANIZATION_ID_FKEY);
    }

    private transient OrganizationsPath _organizations;

    /**
     * Get the implicit join path to the <code>public.organizations</code>
     * table.
     */
    public OrganizationsPath organizations() {
        if (_organizations == null)
            _organizations = new OrganizationsPath(this, Keys.BRIEFS__BRIEFS_ORGANIZATION_ID_FKEY, null);

        return _organizations;
    }

    @Override
    public Briefs as(String alias) {
        return new Briefs(DSL.name(alias), this);
    }

    @Override
    public Briefs as(Name alias) {
        return new Briefs(alias, this);
    }

    @Override
    public Briefs as(Table<?> alias) {
        return new Briefs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Briefs rename(String name) {
        return new Briefs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Briefs rename(Name name) {
        return new Briefs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Briefs rename(Table<?> name) {
        return new Briefs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Briefs where(Condition condition) {
        return new Briefs(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Briefs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Briefs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Briefs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Briefs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Briefs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Briefs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Briefs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Briefs whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Briefs whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
