/*
 * This file is generated by jOOQ.
 */
package dev.theagencyhq.agency.db.jooq.tables;


import dev.theagencyhq.agency.db.jooq.Keys;
import dev.theagencyhq.agency.db.jooq.Public;
import dev.theagencyhq.agency.db.jooq.tables.Organizations.OrganizationsPath;
import dev.theagencyhq.agency.db.jooq.tables.records.BriefSourcesRecord;
import dev.theagencyhq.agency.model.SourceStatus;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Converter;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BriefSources extends TableImpl<BriefSourcesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.brief_sources</code>
     */
    public static final BriefSources BRIEF_SOURCES = new BriefSources();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BriefSourcesRecord> getRecordType() {
        return BriefSourcesRecord.class;
    }

    /**
     * The column <code>public.brief_sources.id</code>.
     */
    public final TableField<BriefSourcesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.brief_sources.organization_id</code>.
     */
    public final TableField<BriefSourcesRecord, UUID> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.brief_sources.path</code>.
     */
    public final TableField<BriefSourcesRecord, String> PATH = createField(DSL.name("path"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.brief_sources.last_built_commit</code>.
     */
    public final TableField<BriefSourcesRecord, String> LAST_BUILT_COMMIT = createField(DSL.name("last_built_commit"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.brief_sources.last_polled_instant</code>.
     */
    public final TableField<BriefSourcesRecord, Instant> LAST_POLLED_INSTANT = createField(DSL.name("last_polled_instant"), SQLDataType.BIGINT, this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    /**
     * The column <code>public.brief_sources.last_status</code>.
     */
    public final TableField<BriefSourcesRecord, SourceStatus> LAST_STATUS = createField(DSL.name("last_status"), SQLDataType.CLOB, this, "", Converter.ofNullable(String.class, SourceStatus.class, t -> t == null ? null : dev.theagencyhq.agency.model.SourceStatus.valueOf(t), u -> u == null ? null : u.name()));

    /**
     * The column <code>public.brief_sources.last_error</code>.
     */
    public final TableField<BriefSourcesRecord, String> LAST_ERROR = createField(DSL.name("last_error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.brief_sources.last_pull_error</code>.
     */
    public final TableField<BriefSourcesRecord, String> LAST_PULL_ERROR = createField(DSL.name("last_pull_error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.brief_sources.insert_instant</code>.
     */
    public final TableField<BriefSourcesRecord, Instant> INSERT_INSTANT = createField(DSL.name("insert_instant"), SQLDataType.BIGINT.nullable(false), this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    /**
     * The column <code>public.brief_sources.update_instant</code>.
     */
    public final TableField<BriefSourcesRecord, Instant> UPDATE_INSTANT = createField(DSL.name("update_instant"), SQLDataType.BIGINT.nullable(false), this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    private BriefSources(Name alias, Table<BriefSourcesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BriefSources(Name alias, Table<BriefSourcesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.brief_sources</code> table reference
     */
    public BriefSources(String alias) {
        this(DSL.name(alias), BRIEF_SOURCES);
    }

    /**
     * Create an aliased <code>public.brief_sources</code> table reference
     */
    public BriefSources(Name alias) {
        this(alias, BRIEF_SOURCES);
    }

    /**
     * Create a <code>public.brief_sources</code> table reference
     */
    public BriefSources() {
        this(DSL.name("brief_sources"), null);
    }

    public <O extends Record> BriefSources(Table<O> path, ForeignKey<O, BriefSourcesRecord> childPath, InverseForeignKey<O, BriefSourcesRecord> parentPath) {
        super(path, childPath, parentPath, BRIEF_SOURCES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BriefSourcesPath extends BriefSources implements Path<BriefSourcesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BriefSourcesPath(Table<O> path, ForeignKey<O, BriefSourcesRecord> childPath, InverseForeignKey<O, BriefSourcesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BriefSourcesPath(Name alias, Table<BriefSourcesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BriefSourcesPath as(String alias) {
            return new BriefSourcesPath(DSL.name(alias), this);
        }

        @Override
        public BriefSourcesPath as(Name alias) {
            return new BriefSourcesPath(alias, this);
        }

        @Override
        public BriefSourcesPath as(Table<?> alias) {
            return new BriefSourcesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<BriefSourcesRecord> getPrimaryKey() {
        return Keys.BRIEF_SOURCES_PKEY;
    }

    @Override
    public List<UniqueKey<BriefSourcesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.BRIEF_SOURCES_ORGANIZATION_ID_KEY, Keys.BRIEF_SOURCES_PATH_KEY);
    }

    @Override
    public List<ForeignKey<BriefSourcesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BRIEF_SOURCES__BRIEF_SOURCES_ORGANIZATION_ID_FKEY);
    }

    private transient OrganizationsPath _organizations;

    /**
     * Get the implicit join path to the <code>public.organizations</code>
     * table.
     */
    public OrganizationsPath organizations() {
        if (_organizations == null)
            _organizations = new OrganizationsPath(this, Keys.BRIEF_SOURCES__BRIEF_SOURCES_ORGANIZATION_ID_FKEY, null);

        return _organizations;
    }

    @Override
    public List<Check<BriefSourcesRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("brief_sources_last_status_check"), "((last_status = ANY (ARRAY['BUILD_FAILED'::text, 'NOT_A_REPOSITORY'::text, 'OK'::text, 'UNCHANGED'::text])))", true)
        );
    }

    @Override
    public BriefSources as(String alias) {
        return new BriefSources(DSL.name(alias), this);
    }

    @Override
    public BriefSources as(Name alias) {
        return new BriefSources(alias, this);
    }

    @Override
    public BriefSources as(Table<?> alias) {
        return new BriefSources(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BriefSources rename(String name) {
        return new BriefSources(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BriefSources rename(Name name) {
        return new BriefSources(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BriefSources rename(Table<?> name) {
        return new BriefSources(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BriefSources where(Condition condition) {
        return new BriefSources(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BriefSources where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BriefSources where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BriefSources where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BriefSources where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BriefSources where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BriefSources where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BriefSources where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BriefSources whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BriefSources whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
