/*
 * This file is generated by jOOQ.
 */
package dev.theagencyhq.agency.db.jooq.tables;


import dev.theagencyhq.agency.db.jooq.Indexes;
import dev.theagencyhq.agency.db.jooq.Keys;
import dev.theagencyhq.agency.db.jooq.Public;
import dev.theagencyhq.agency.db.jooq.tables.Organizations.OrganizationsPath;
import dev.theagencyhq.agency.db.jooq.tables.records.MembersRecord;
import dev.theagencyhq.agency.model.MembershipState;
import dev.theagencyhq.agency.model.Role;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Converter;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Members extends TableImpl<MembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.members</code>
     */
    public static final Members MEMBERS = new Members();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MembersRecord> getRecordType() {
        return MembersRecord.class;
    }

    /**
     * The column <code>public.members.organization_id</code>.
     */
    public final TableField<MembersRecord, UUID> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.members.user_id</code>.
     */
    public final TableField<MembersRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.members.role</code>.
     */
    public final TableField<MembersRecord, Role> ROLE = createField(DSL.name("role"), SQLDataType.CLOB.nullable(false), this, "", Converter.ofNullable(String.class, Role.class, t -> t == null ? null : dev.theagencyhq.agency.model.Role.valueOf(t), u -> u == null ? null : u.name()));

    /**
     * The column <code>public.members.state</code>.
     */
    public final TableField<MembersRecord, MembershipState> STATE = createField(DSL.name("state"), SQLDataType.CLOB.nullable(false), this, "", Converter.ofNullable(String.class, MembershipState.class, t -> t == null ? null : dev.theagencyhq.agency.model.MembershipState.valueOf(t), u -> u == null ? null : u.name()));

    /**
     * The column <code>public.members.invited_by</code>.
     */
    public final TableField<MembersRecord, UUID> INVITED_BY = createField(DSL.name("invited_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.members.invited_at</code>.
     */
    public final TableField<MembersRecord, Instant> INVITED_AT = createField(DSL.name("invited_at"), SQLDataType.BIGINT, this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    /**
     * The column <code>public.members.joined_at</code>.
     */
    public final TableField<MembersRecord, Instant> JOINED_AT = createField(DSL.name("joined_at"), SQLDataType.BIGINT, this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    private Members(Name alias, Table<MembersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Members(Name alias, Table<MembersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.members</code> table reference
     */
    public Members(String alias) {
        this(DSL.name(alias), MEMBERS);
    }

    /**
     * Create an aliased <code>public.members</code> table reference
     */
    public Members(Name alias) {
        this(alias, MEMBERS);
    }

    /**
     * Create a <code>public.members</code> table reference
     */
    public Members() {
        this(DSL.name("members"), null);
    }

    public <O extends Record> Members(Table<O> path, ForeignKey<O, MembersRecord> childPath, InverseForeignKey<O, MembersRecord> parentPath) {
        super(path, childPath, parentPath, MEMBERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MembersPath extends Members implements Path<MembersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MembersPath(Table<O> path, ForeignKey<O, MembersRecord> childPath, InverseForeignKey<O, MembersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MembersPath(Name alias, Table<MembersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MembersPath as(String alias) {
            return new MembersPath(DSL.name(alias), this);
        }

        @Override
        public MembersPath as(Name alias) {
            return new MembersPath(alias, this);
        }

        @Override
        public MembersPath as(Table<?> alias) {
            return new MembersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MEMBERS_IDX_USER_ID);
    }

    @Override
    public UniqueKey<MembersRecord> getPrimaryKey() {
        return Keys.MEMBERS_PKEY;
    }

    @Override
    public List<ForeignKey<MembersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEMBERS__MEMBERS_ORGANIZATION_ID_FKEY);
    }

    private transient OrganizationsPath _organizations;

    /**
     * Get the implicit join path to the <code>public.organizations</code>
     * table.
     */
    public OrganizationsPath organizations() {
        if (_organizations == null)
            _organizations = new OrganizationsPath(this, Keys.MEMBERS__MEMBERS_ORGANIZATION_ID_FKEY, null);

        return _organizations;
    }

    @Override
    public List<Check<MembersRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("members_role_check"), "((role = ANY (ARRAY['CONTRIBUTOR'::text, 'OWNER'::text])))", true),
            Internal.createCheck(this, DSL.name("members_state_check"), "((state = ANY (ARRAY['ACTIVE'::text, 'PENDING'::text])))", true)
        );
    }

    @Override
    public Members as(String alias) {
        return new Members(DSL.name(alias), this);
    }

    @Override
    public Members as(Name alias) {
        return new Members(alias, this);
    }

    @Override
    public Members as(Table<?> alias) {
        return new Members(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Members rename(String name) {
        return new Members(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Members rename(Name name) {
        return new Members(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Members rename(Table<?> name) {
        return new Members(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Members where(Condition condition) {
        return new Members(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Members where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Members where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Members where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Members where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Members where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Members where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Members where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Members whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Members whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
