/*
 * This file is generated by jOOQ.
 */
package dev.theagencyhq.agency.db.jooq.tables;


import dev.theagencyhq.agency.db.jooq.Keys;
import dev.theagencyhq.agency.db.jooq.Public;
import dev.theagencyhq.agency.db.jooq.tables.BriefSources.BriefSourcesPath;
import dev.theagencyhq.agency.db.jooq.tables.Briefs.BriefsPath;
import dev.theagencyhq.agency.db.jooq.tables.records.OrganizationsRecord;

import java.time.Instant;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Converter;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Organizations extends TableImpl<OrganizationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.organizations</code>
     */
    public static final Organizations ORGANIZATIONS = new Organizations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganizationsRecord> getRecordType() {
        return OrganizationsRecord.class;
    }

    /**
     * The column <code>public.organizations.id</code>.
     */
    public final TableField<OrganizationsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.organizations.name</code>.
     */
    public final TableField<OrganizationsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.organizations.insert_instant</code>.
     */
    public final TableField<OrganizationsRecord, Instant> INSERT_INSTANT = createField(DSL.name("insert_instant"), SQLDataType.BIGINT.nullable(false), this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    /**
     * The column <code>public.organizations.update_instant</code>.
     */
    public final TableField<OrganizationsRecord, Instant> UPDATE_INSTANT = createField(DSL.name("update_instant"), SQLDataType.BIGINT.nullable(false), this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    private Organizations(Name alias, Table<OrganizationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Organizations(Name alias, Table<OrganizationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.organizations</code> table reference
     */
    public Organizations(String alias) {
        this(DSL.name(alias), ORGANIZATIONS);
    }

    /**
     * Create an aliased <code>public.organizations</code> table reference
     */
    public Organizations(Name alias) {
        this(alias, ORGANIZATIONS);
    }

    /**
     * Create a <code>public.organizations</code> table reference
     */
    public Organizations() {
        this(DSL.name("organizations"), null);
    }

    public <O extends Record> Organizations(Table<O> path, ForeignKey<O, OrganizationsRecord> childPath, InverseForeignKey<O, OrganizationsRecord> parentPath) {
        super(path, childPath, parentPath, ORGANIZATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrganizationsPath extends Organizations implements Path<OrganizationsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrganizationsPath(Table<O> path, ForeignKey<O, OrganizationsRecord> childPath, InverseForeignKey<O, OrganizationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrganizationsPath(Name alias, Table<OrganizationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrganizationsPath as(String alias) {
            return new OrganizationsPath(DSL.name(alias), this);
        }

        @Override
        public OrganizationsPath as(Name alias) {
            return new OrganizationsPath(alias, this);
        }

        @Override
        public OrganizationsPath as(Table<?> alias) {
            return new OrganizationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OrganizationsRecord> getPrimaryKey() {
        return Keys.ORGANIZATIONS_PKEY;
    }

    private transient BriefSourcesPath _briefSources;

    /**
     * Get the implicit to-many join path to the
     * <code>public.brief_sources</code> table
     */
    public BriefSourcesPath briefSources() {
        if (_briefSources == null)
            _briefSources = new BriefSourcesPath(this, null, Keys.BRIEF_SOURCES__BRIEF_SOURCES_ORGANIZATION_ID_FKEY.getInverseKey());

        return _briefSources;
    }

    private transient BriefsPath _briefs;

    /**
     * Get the implicit to-many join path to the <code>public.briefs</code>
     * table
     */
    public BriefsPath briefs() {
        if (_briefs == null)
            _briefs = new BriefsPath(this, null, Keys.BRIEFS__BRIEFS_ORGANIZATION_ID_FKEY.getInverseKey());

        return _briefs;
    }

    @Override
    public Organizations as(String alias) {
        return new Organizations(DSL.name(alias), this);
    }

    @Override
    public Organizations as(Name alias) {
        return new Organizations(alias, this);
    }

    @Override
    public Organizations as(Table<?> alias) {
        return new Organizations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Organizations rename(String name) {
        return new Organizations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organizations rename(Name name) {
        return new Organizations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organizations rename(Table<?> name) {
        return new Organizations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organizations where(Condition condition) {
        return new Organizations(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organizations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organizations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organizations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organizations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organizations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organizations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organizations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organizations whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organizations whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
